// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/events (interfaces: ProjectCommandRunner)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	command "github.com/runatlantis/atlantis/server/events/command"
)

// MockProjectCommandRunner is a mock of ProjectCommandRunner interface.
type MockProjectCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockProjectCommandRunnerMockRecorder
}

// MockProjectCommandRunnerMockRecorder is the mock recorder for MockProjectCommandRunner.
type MockProjectCommandRunnerMockRecorder struct {
	mock *MockProjectCommandRunner
}

// NewMockProjectCommandRunner creates a new mock instance.
func NewMockProjectCommandRunner(ctrl *gomock.Controller) *MockProjectCommandRunner {
	mock := &MockProjectCommandRunner{ctrl: ctrl}
	mock.recorder = &MockProjectCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectCommandRunner) EXPECT() *MockProjectCommandRunnerMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockProjectCommandRunner) Apply(arg0 command.ProjectContext) command.ProjectResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", arg0)
	ret0, _ := ret[0].(command.ProjectResult)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockProjectCommandRunnerMockRecorder) Apply(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockProjectCommandRunner)(nil).Apply), arg0)
}

// ApprovePolicies mocks base method.
func (m *MockProjectCommandRunner) ApprovePolicies(arg0 command.ProjectContext) command.ProjectResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePolicies", arg0)
	ret0, _ := ret[0].(command.ProjectResult)
	return ret0
}

// ApprovePolicies indicates an expected call of ApprovePolicies.
func (mr *MockProjectCommandRunnerMockRecorder) ApprovePolicies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePolicies", reflect.TypeOf((*MockProjectCommandRunner)(nil).ApprovePolicies), arg0)
}

// Plan mocks base method.
func (m *MockProjectCommandRunner) Plan(arg0 command.ProjectContext) command.ProjectResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plan", arg0)
	ret0, _ := ret[0].(command.ProjectResult)
	return ret0
}

// Plan indicates an expected call of Plan.
func (mr *MockProjectCommandRunnerMockRecorder) Plan(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plan", reflect.TypeOf((*MockProjectCommandRunner)(nil).Plan), arg0)
}

// PolicyCheck mocks base method.
func (m *MockProjectCommandRunner) PolicyCheck(arg0 command.ProjectContext) command.ProjectResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PolicyCheck", arg0)
	ret0, _ := ret[0].(command.ProjectResult)
	return ret0
}

// PolicyCheck indicates an expected call of PolicyCheck.
func (mr *MockProjectCommandRunnerMockRecorder) PolicyCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyCheck", reflect.TypeOf((*MockProjectCommandRunner)(nil).PolicyCheck), arg0)
}

// Version mocks base method.
func (m *MockProjectCommandRunner) Version(arg0 command.ProjectContext) command.ProjectResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version", arg0)
	ret0, _ := ret[0].(command.ProjectResult)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockProjectCommandRunnerMockRecorder) Version(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockProjectCommandRunner)(nil).Version), arg0)
}
