// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/events (interfaces: WebhooksSender)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	webhooks "github.com/runatlantis/atlantis/server/events/webhooks"
	logging "github.com/runatlantis/atlantis/server/logging"
)

// MockWebhooksSender is a mock of WebhooksSender interface.
type MockWebhooksSender struct {
	ctrl     *gomock.Controller
	recorder *MockWebhooksSenderMockRecorder
}

// MockWebhooksSenderMockRecorder is the mock recorder for MockWebhooksSender.
type MockWebhooksSenderMockRecorder struct {
	mock *MockWebhooksSender
}

// NewMockWebhooksSender creates a new mock instance.
func NewMockWebhooksSender(ctrl *gomock.Controller) *MockWebhooksSender {
	mock := &MockWebhooksSender{ctrl: ctrl}
	mock.recorder = &MockWebhooksSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhooksSender) EXPECT() *MockWebhooksSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWebhooksSender) Send(arg0 logging.SimpleLogging, arg1 webhooks.ApplyResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockWebhooksSenderMockRecorder) Send(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWebhooksSender)(nil).Send), arg0, arg1)
}
