// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/events (interfaces: JobURLSetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	command "github.com/runatlantis/atlantis/server/events/command"
	models "github.com/runatlantis/atlantis/server/events/models"
)

// MockJobURLSetter is a mock of JobURLSetter interface.
type MockJobURLSetter struct {
	ctrl     *gomock.Controller
	recorder *MockJobURLSetterMockRecorder
}

// MockJobURLSetterMockRecorder is the mock recorder for MockJobURLSetter.
type MockJobURLSetterMockRecorder struct {
	mock *MockJobURLSetter
}

// NewMockJobURLSetter creates a new mock instance.
func NewMockJobURLSetter(ctrl *gomock.Controller) *MockJobURLSetter {
	mock := &MockJobURLSetter{ctrl: ctrl}
	mock.recorder = &MockJobURLSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobURLSetter) EXPECT() *MockJobURLSetterMockRecorder {
	return m.recorder
}

// SetJobURLWithStatus mocks base method.
func (m *MockJobURLSetter) SetJobURLWithStatus(arg0 command.ProjectContext, arg1 command.Name, arg2 models.CommitStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJobURLWithStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJobURLWithStatus indicates an expected call of SetJobURLWithStatus.
func (mr *MockJobURLSetterMockRecorder) SetJobURLWithStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobURLWithStatus", reflect.TypeOf((*MockJobURLSetter)(nil).SetJobURLWithStatus), arg0, arg1, arg2)
}
