// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/events (interfaces: EnvStepRunner)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	command "github.com/runatlantis/atlantis/server/events/command"
)

// MockEnvStepRunner is a mock of EnvStepRunner interface.
type MockEnvStepRunner struct {
	ctrl     *gomock.Controller
	recorder *MockEnvStepRunnerMockRecorder
}

// MockEnvStepRunnerMockRecorder is the mock recorder for MockEnvStepRunner.
type MockEnvStepRunnerMockRecorder struct {
	mock *MockEnvStepRunner
}

// NewMockEnvStepRunner creates a new mock instance.
func NewMockEnvStepRunner(ctrl *gomock.Controller) *MockEnvStepRunner {
	mock := &MockEnvStepRunner{ctrl: ctrl}
	mock.recorder = &MockEnvStepRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvStepRunner) EXPECT() *MockEnvStepRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockEnvStepRunner) Run(arg0 command.ProjectContext, arg1, arg2, arg3 string, arg4 map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockEnvStepRunnerMockRecorder) Run(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockEnvStepRunner)(nil).Run), arg0, arg1, arg2, arg3, arg4)
}
