// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/events (interfaces: PendingPlanFinder)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	events "github.com/runatlantis/atlantis/server/events"
)

// MockPendingPlanFinder is a mock of PendingPlanFinder interface.
type MockPendingPlanFinder struct {
	ctrl     *gomock.Controller
	recorder *MockPendingPlanFinderMockRecorder
}

// MockPendingPlanFinderMockRecorder is the mock recorder for MockPendingPlanFinder.
type MockPendingPlanFinderMockRecorder struct {
	mock *MockPendingPlanFinder
}

// NewMockPendingPlanFinder creates a new mock instance.
func NewMockPendingPlanFinder(ctrl *gomock.Controller) *MockPendingPlanFinder {
	mock := &MockPendingPlanFinder{ctrl: ctrl}
	mock.recorder = &MockPendingPlanFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingPlanFinder) EXPECT() *MockPendingPlanFinderMockRecorder {
	return m.recorder
}

// DeletePlans mocks base method.
func (m *MockPendingPlanFinder) DeletePlans(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlans", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlans indicates an expected call of DeletePlans.
func (mr *MockPendingPlanFinderMockRecorder) DeletePlans(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlans", reflect.TypeOf((*MockPendingPlanFinder)(nil).DeletePlans), arg0)
}

// Find mocks base method.
func (m *MockPendingPlanFinder) Find(arg0 string) ([]events.PendingPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].([]events.PendingPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPendingPlanFinderMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPendingPlanFinder)(nil).Find), arg0)
}
