// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/core/locking (interfaces: Backend)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	command "github.com/runatlantis/atlantis/server/events/command"
	models "github.com/runatlantis/atlantis/server/events/models"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// CheckCommandLock mocks base method.
func (m *MockBackend) CheckCommandLock(arg0 command.Name) (*command.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCommandLock", arg0)
	ret0, _ := ret[0].(*command.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCommandLock indicates an expected call of CheckCommandLock.
func (mr *MockBackendMockRecorder) CheckCommandLock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCommandLock", reflect.TypeOf((*MockBackend)(nil).CheckCommandLock), arg0)
}

// DeletePullStatus mocks base method.
func (m *MockBackend) DeletePullStatus(arg0 models.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePullStatus", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePullStatus indicates an expected call of DeletePullStatus.
func (mr *MockBackendMockRecorder) DeletePullStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePullStatus", reflect.TypeOf((*MockBackend)(nil).DeletePullStatus), arg0)
}

// GetLock mocks base method.
func (m *MockBackend) GetLock(arg0 models.Project, arg1 string) (*models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLock", arg0, arg1)
	ret0, _ := ret[0].(*models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLock indicates an expected call of GetLock.
func (mr *MockBackendMockRecorder) GetLock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLock", reflect.TypeOf((*MockBackend)(nil).GetLock), arg0, arg1)
}

// GetPullStatus mocks base method.
func (m *MockBackend) GetPullStatus(arg0 models.PullRequest) (*models.PullStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullStatus", arg0)
	ret0, _ := ret[0].(*models.PullStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullStatus indicates an expected call of GetPullStatus.
func (mr *MockBackendMockRecorder) GetPullStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullStatus", reflect.TypeOf((*MockBackend)(nil).GetPullStatus), arg0)
}

// List mocks base method.
func (m *MockBackend) List() ([]models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBackendMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBackend)(nil).List))
}

// LockCommand mocks base method.
func (m *MockBackend) LockCommand(arg0 command.Name, arg1 time.Time) (*command.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockCommand", arg0, arg1)
	ret0, _ := ret[0].(*command.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockCommand indicates an expected call of LockCommand.
func (mr *MockBackendMockRecorder) LockCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockCommand", reflect.TypeOf((*MockBackend)(nil).LockCommand), arg0, arg1)
}

// TryLock mocks base method.
func (m *MockBackend) TryLock(arg0 models.ProjectLock) (bool, models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryLock", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(models.ProjectLock)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryLock indicates an expected call of TryLock.
func (mr *MockBackendMockRecorder) TryLock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryLock", reflect.TypeOf((*MockBackend)(nil).TryLock), arg0)
}

// Unlock mocks base method.
func (m *MockBackend) Unlock(arg0 models.Project, arg1 string) (*models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", arg0, arg1)
	ret0, _ := ret[0].(*models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unlock indicates an expected call of Unlock.
func (mr *MockBackendMockRecorder) Unlock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockBackend)(nil).Unlock), arg0, arg1)
}

// UnlockByPull mocks base method.
func (m *MockBackend) UnlockByPull(arg0 string, arg1 int) ([]models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockByPull", arg0, arg1)
	ret0, _ := ret[0].([]models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockByPull indicates an expected call of UnlockByPull.
func (mr *MockBackendMockRecorder) UnlockByPull(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockByPull", reflect.TypeOf((*MockBackend)(nil).UnlockByPull), arg0, arg1)
}

// UnlockCommand mocks base method.
func (m *MockBackend) UnlockCommand(arg0 command.Name) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockCommand", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockCommand indicates an expected call of UnlockCommand.
func (mr *MockBackendMockRecorder) UnlockCommand(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockCommand", reflect.TypeOf((*MockBackend)(nil).UnlockCommand), arg0)
}

// UpdateProjectStatus mocks base method.
func (m *MockBackend) UpdateProjectStatus(arg0 models.PullRequest, arg1, arg2 string, arg3 models.ProjectPlanStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProjectStatus indicates an expected call of UpdateProjectStatus.
func (mr *MockBackendMockRecorder) UpdateProjectStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectStatus", reflect.TypeOf((*MockBackend)(nil).UpdateProjectStatus), arg0, arg1, arg2, arg3)
}

// UpdatePullWithResults mocks base method.
func (m *MockBackend) UpdatePullWithResults(arg0 models.PullRequest, arg1 []command.ProjectResult) (models.PullStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullWithResults", arg0, arg1)
	ret0, _ := ret[0].(models.PullStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePullWithResults indicates an expected call of UpdatePullWithResults.
func (mr *MockBackendMockRecorder) UpdatePullWithResults(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullWithResults", reflect.TypeOf((*MockBackend)(nil).UpdatePullWithResults), arg0, arg1)
}
