// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/core/runtime/models (interfaces: FilePath)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/runatlantis/atlantis/server/core/runtime/models"
)

// MockFilePath is a mock of FilePath interface.
type MockFilePath struct {
	ctrl     *gomock.Controller
	recorder *MockFilePathMockRecorder
}

// MockFilePathMockRecorder is the mock recorder for MockFilePath.
type MockFilePathMockRecorder struct {
	mock *MockFilePath
}

// NewMockFilePath creates a new mock instance.
func NewMockFilePath(ctrl *gomock.Controller) *MockFilePath {
	mock := &MockFilePath{ctrl: ctrl}
	mock.recorder = &MockFilePathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilePath) EXPECT() *MockFilePathMockRecorder {
	return m.recorder
}

// Join mocks base method.
func (m *MockFilePath) Join(arg0 ...string) models.FilePath {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(models.FilePath)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockFilePathMockRecorder) Join(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockFilePath)(nil).Join), arg0...)
}

// NotExists mocks base method.
func (m *MockFilePath) NotExists() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotExists")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NotExists indicates an expected call of NotExists.
func (mr *MockFilePathMockRecorder) NotExists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotExists", reflect.TypeOf((*MockFilePath)(nil).NotExists))
}

// Resolve mocks base method.
func (m *MockFilePath) Resolve() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve")
	ret0, _ := ret[0].(string)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockFilePathMockRecorder) Resolve() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockFilePath)(nil).Resolve))
}

// Symlink mocks base method.
func (m *MockFilePath) Symlink(arg0 string) (models.FilePath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", arg0)
	ret0, _ := ret[0].(models.FilePath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Symlink indicates an expected call of Symlink.
func (mr *MockFilePathMockRecorder) Symlink(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockFilePath)(nil).Symlink), arg0)
}
