// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/core/runtime (interfaces: PostWorkflowHookRunner)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/runatlantis/atlantis/server/events/models"
)

// MockPostWorkflowHookRunner is a mock of PostWorkflowHookRunner interface.
type MockPostWorkflowHookRunner struct {
	ctrl     *gomock.Controller
	recorder *MockPostWorkflowHookRunnerMockRecorder
}

// MockPostWorkflowHookRunnerMockRecorder is the mock recorder for MockPostWorkflowHookRunner.
type MockPostWorkflowHookRunnerMockRecorder struct {
	mock *MockPostWorkflowHookRunner
}

// NewMockPostWorkflowHookRunner creates a new mock instance.
func NewMockPostWorkflowHookRunner(ctrl *gomock.Controller) *MockPostWorkflowHookRunner {
	mock := &MockPostWorkflowHookRunner{ctrl: ctrl}
	mock.recorder = &MockPostWorkflowHookRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostWorkflowHookRunner) EXPECT() *MockPostWorkflowHookRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockPostWorkflowHookRunner) Run(arg0 models.WorkflowHookCommandContext, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockPostWorkflowHookRunnerMockRecorder) Run(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPostWorkflowHookRunner)(nil).Run), arg0, arg1, arg2)
}
