// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/jobs (interfaces: ProjectJobURLGenerator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	command "github.com/runatlantis/atlantis/server/events/command"
)

// MockProjectJobURLGenerator is a mock of ProjectJobURLGenerator interface.
type MockProjectJobURLGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockProjectJobURLGeneratorMockRecorder
}

// MockProjectJobURLGeneratorMockRecorder is the mock recorder for MockProjectJobURLGenerator.
type MockProjectJobURLGeneratorMockRecorder struct {
	mock *MockProjectJobURLGenerator
}

// NewMockProjectJobURLGenerator creates a new mock instance.
func NewMockProjectJobURLGenerator(ctrl *gomock.Controller) *MockProjectJobURLGenerator {
	mock := &MockProjectJobURLGenerator{ctrl: ctrl}
	mock.recorder = &MockProjectJobURLGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectJobURLGenerator) EXPECT() *MockProjectJobURLGeneratorMockRecorder {
	return m.recorder
}

// GenerateProjectJobURL mocks base method.
func (m *MockProjectJobURLGenerator) GenerateProjectJobURL(arg0 command.ProjectContext) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateProjectJobURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateProjectJobURL indicates an expected call of GenerateProjectJobURL.
func (mr *MockProjectJobURLGeneratorMockRecorder) GenerateProjectJobURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateProjectJobURL", reflect.TypeOf((*MockProjectJobURLGenerator)(nil).GenerateProjectJobURL), arg0)
}
